layout_spectrum: 0
typography_spectrum: 0.4910394
color:
  saturation: 0.1268135
  lightness: 0.4551971
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#CECECE'
    - '#393939'
    - '#6D6D6D'
  rhythmicContrast: 0.7107055
name: PRO MUSIC MASTERING
